name: Check coding style

on: [push]

jobs:
  pycodestyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: pycodestyle
      run: |
        pycodestyle
  pydocstyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydocstyle
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: pydocstyle
      run: |
        pydocstyle
